# Generated by Django 3.2.5 on 2021-08-15 11:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal', '0002_auto_20210808_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiteruser',
            name='about',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='recruiteruser',
            name='company_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='recruiteruser',
            name='establish_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('resume', models.FileField(null=True, upload_to='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job_Portal.jobs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job_Portal.studentuser')),
            ],
        ),
    ]
