# Generated by Django 3.2.5 on 2021-08-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal', '0003_auto_20210815_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
