# Generated by Django 3.2.5 on 2021-08-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal', '0004_jobs_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='recruiteruser',
            name='recruiter_logo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='candidate_logo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
