# Generated by Django 3.2.5 on 2021-09-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal', '0005_auto_20210831_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiteruser',
            name='recruiter_logo',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='candidate_logo',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
