# Generated by Django 3.2.5 on 2021-09-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal', '0008_auto_20210901_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiteruser',
            name='recruiter_logo',
            field=models.FileField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='candidate_logo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
