# Generated by Django 3.2.5 on 2021-09-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal', '0009_auto_20210901_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company_logo',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
