# Generated by Django 3.2.5 on 2021-09-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal', '0012_remove_job_category_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='about_company',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recruiteruser',
            name='about',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
