# Generated by Django 3.2.5 on 2021-09-05 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal', '0013_auto_20210904_2352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_category',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='jobs',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Job_Portal.category'),
        ),
    ]
