# Generated by Django 3.2.5 on 2021-09-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal', '0014_auto_20210905_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='cover_letter',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='hire_why',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
