# Generated by Django 3.2.5 on 2021-09-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal', '0015_auto_20210910_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='category',
        ),
    ]
