# Generated by Django 3.2.5 on 2021-09-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal', '0016_remove_jobs_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='org_type',
            field=models.CharField(max_length=110, null=True),
        ),
    ]
